brokerExchange: amq.topic
brokerIP: CPEb0faebda0289-CM00fc8d75ac20.cpe.net.cable.rogers.com
brokerUser: jamie
deviceId: 58:00:E3:F6:96:50
deviceName: ITECH_H.R. Portal
encrypt: false
firstData: 13
librarianExchange: LIBRARIAN_RPC
librarianExchangeType: direct
librarianQueue: rpc_queue
localArchivePath: archive.txt
location: London Ontario
myDBID: e5a0d9ef-e1b2-4c1f-8283-ced6208ae7e9
password: popeye
pathToCertificate: ''
pathToKey: ''
qt: true
rmqServer: false
tenant: 00000000-0000-0000-0000-000000000000
userName: i-tech
