brokerExchange: amq.topic
brokerIP: 192.168.0.11
brokerUser: jamie
deviceId: 58:00:E3:F6:96:50
deviceName: ITECH_H.R. Portal
encrypt: false
firstData: 13
librarianExchange: LIBRARIAN_RPC
librarianExchangeType: direct
librarianQueue: rpc_queue
localArchivePath: archive.txt
location: London Ontario
myDBID: e5a0d9ef-e1b2-4c1f-8283-ced6208ae7e9
password: popeye
pathToCertificate: ''
pathToKey: ''
payCycle: weekly
qt: true
rmqServer: false
seedPayDay: '2012-01-18'
tenant: 00000000-0000-0000-0000-000000000000
userName: i-tech
yearStartMonth: '04'
